### ISSUE TITLE
Fix style for Select2 (Minor visual glitch)

### ISSUE THREAD

**Issue by siamkreative** [ThemeAvenue/Behavior-Flow#5]
![image](https://cloud.githubusercontent.com/assets/1778633/9779757/780a340c-57a9-11e5-81f4-1d4e388f2490.png)

The issue seems to be caused by the following:

``` css
.select2-container .select2-selection--single {
    margin: 1px;
}
```
